name: Tests

on:
  push:
    branches:
      - main
      - dev
    tags:
      - v*
  pull_request:
  schedule:
    - cron: "0 1 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.9']
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install -r requirements.dev.txt
      - name: Run tests
        working-directory: .
        run: python -m unittest
        env:
          TGTG_USERNAME: ${{secrets.TGTG_USERNAME}}
          TGTG_ACCESS_TOKEN: ${{secrets.TGTG_ACCESS_TOKEN}}
          TGTG_REFRESH_TOKEN: ${{secrets.TGTG_REFRESH_TOKEN}}
          TGTG_USER_ID: ${{secrets.TGTG_USER_ID}}
          REPO_ACCESS_TOKEN: ${{secrets.REPO_ACCESS_TOKEN}}
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'TGTG_ACCESS_TOKEN'
          value: ${{env.TGTG_ACCESS_TOKEN}}
          repository: Der-Henning/tgtg
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'TGTG_REFRESH_TOKEN'
          value: ${{env.TGTG_REFRESH_TOKEN}}
          repository: Der-Henning/tgtg
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'TGTG_USER_ID'
          value: ${{env.TGTG_USER_ID}}
          repository: Der-Henning/tgtg
          token: ${{ secrets.REPO_ACCESS_TOKEN }}